const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

test('Cosmological pseudo-questions publication links preserve both language titles', () => {
  for (const [file, title, editing] of [
    ['index.html', 'Cosmological Pseudo-Questions Generated by Life-Death Cognition', '(In editing)'],
    ['jp/index.html', '人間の生死認知が生む宇宙論的誤問題', '（編集中）'],
  ]) {
    const html = fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
    const entry = html.match(/<li><a href="https:\/\/doi\.org\/10\.5281\/zenodo\.22779708"[^>]*>[\s\S]*?<\/a><\/li>/)?.[0];
    assert.ok(entry, file);
    assert.ok(entry.includes(title));
    assert.ok(!entry.includes(editing));
    assert.ok(entry.includes('<br>'));
  }
});

test('Cosmological pseudo-questions belongs to structural cognition', () => {
  const categories = JSON.parse(fs.readFileSync(path.join(__dirname, '../data/zenodo/paper_categories.json'), 'utf8'));
  assert.equal(categories.papers['10.5281/zenodo.22779708'], 'Cognitive Science / Structural Cognition');
});
